Data Frames =>Combo of multiple series

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "name":["Asmin","Nitik","Ramesh","Linda"],
    "age":[20,21,22,23],
    "city":["klpr","Npj","skt","ktm"],
    "salaray":[20000.1,22000.3,12000.12,200000.3232]
}
data

{'name': ['Asmin', 'Nitik', 'Ramesh', 'Linda'],
 'age': [20, 21, 22, 23],
 'city': ['klpr', 'Npj', 'skt', 'ktm'],
 'salaray': [20000.1, 22000.3, 12000.12, 200000.3232]}

In [5]:
pd.DataFrame(data)

     name  age  city      salaray
0   Asmin   20  klpr   20000.1000
1   Nitik   21   Npj   22000.3000
2  Ramesh   22   skt   12000.1200
3   Linda   23   ktm  200000.3232

In [6]:

data = [

    ["Asmin", 20, "klpr", 20000.1],
    ["Nitik", 21, "Npj", 22000.3],
    ["Ramesh", 22, "skt", 12000.12],
    ["Linda", 23, "ktm", 200000.3232]
]

df1=pd.DataFrame(data)
colum = ["Name","Age","City","Salary"]

df2 = pd.DataFrame(data,columns=colum)
print(df2)

     Name  Age  City       Salary
0   Asmin   20  klpr   20000.1000
1   Nitik   21   Npj   22000.3000
2  Ramesh   22   skt   12000.1200
3   Linda   23   ktm  200000.3232

In [7]:
### Select only name
print(df2["Name"])
print(df2[["Name","City"]])

0     Asmin
1     Nitik
2    Ramesh
3     Linda
Name: Name, dtype: str
     Name  City
0   Asmin  klpr
1   Nitik   Npj
2  Ramesh   skt
3   Linda   ktm

###  Add New Column

In [8]:
df2["Program"] = ["Go","Python","Java","Flutter"]
df2

     Name  Age  City       Salary  Program
0   Asmin   20  klpr   20000.1000       Go
1   Nitik   21   Npj   22000.3000   Python
2  Ramesh   22   skt   12000.1200     Java
3   Linda   23   ktm  200000.3232  Flutter

In [9]:
## Remove Colum axis 0 row
df2.drop("Program",axis=1)

### Inplace =True delete permanently
### after remove it show a temp time in later it show

     Name  Age  City       Salary
0   Asmin   20  klpr   20000.1000
1   Nitik   21   Npj   22000.3000
2  Ramesh   22   skt   12000.1200
3   Linda   23   ktm  200000.3232

In [10]:
# df2.drop("Program",axis=1)
df2.drop(3,axis=0)

     Name  Age  City    Salary Program
0   Asmin   20  klpr  20000.10      Go
1   Nitik   21   Npj  22000.30  Python
2  Ramesh   22   skt  12000.12    Java

In [11]:
df2

     Name  Age  City       Salary  Program
0   Asmin   20  klpr   20000.1000       Go
1   Nitik   21   Npj   22000.3000   Python
2  Ramesh   22   skt   12000.1200     Java
3   Linda   23   ktm  200000.3232  Flutter

Selecting a Row

In [12]:
df2.loc[[0,1]]

    Name  Age  City   Salary Program
0  Asmin   20  klpr  20000.1      Go
1  Nitik   21   Npj  22000.3  Python

In [13]:
df2

     Name  Age  City       Salary  Program
0   Asmin   20  klpr   20000.1000       Go
1   Nitik   21   Npj   22000.3000   Python
2  Ramesh   22   skt   12000.1200     Java
3   Linda   23   ktm  200000.3232  Flutter

In [ ]:
### Select the people whose ages greater then 20
df2[df2["Age"]>20]

     Name  Age City       Salary  Program
1   Nitik   21  Npj   22000.3000   Python
2  Ramesh   22  skt   12000.1200     Java
3   Linda   23  ktm  200000.3232  Flutter

In [20]:
df2[(df2["Age"]>20) & (df2["City"]=="ktm")]

    Name  Age City       Salary  Program
3  Linda   23  ktm  200000.3232  Flutter