Features Extraction

In [1]:
import numpy as np
import pandas as pd

In [3]:
### Load a data
data = pd.read_csv("./anime_data.csv")
data

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi, Adult Cast, Space","Crime is timeless. By the year 2071, humanity ...",TV,26,"Apr 3, 1998 to Apr 24, 1999",...,Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),50,41,90976,1077271,2089081,https://cdn.myanimelist.net/images/anime/4/196...
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi, Adult Cast, Space","Another day, another bounty—such is the life o...",Movie,1,"Sep 1, 2001",...,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),252,663,1827,234731,417292,https://cdn.myanimelist.net/images/anime/1439/...
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi, Adult Cast, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",...,Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,433,268,17956,405835,846067,https://cdn.myanimelist.net/images/anime/1130/...
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.24,"Action, Drama, Mystery, Supernatural, Detective","Though hidden away from the general public, Wi...",TV,26,"Jul 3, 2002 to Dec 25, 2002",...,Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,3558,2003,720,46691,132072,https://cdn.myanimelist.net/images/anime/10/19...
4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,6.97,"Action, Adventure, Fantasy, Shounen",It is the dark century and the people are suff...,TV,52,"Sep 30, 2004 to Sep 29, 2005",...,Toei Animation,Manga,23 min. per ep.,PG - Children,5016,6031,18,6983,16793,https://cdn.myanimelist.net/images/anime/7/215...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30758,65097,AIYOU,AIYOU,AIYOU,UNKNOWN,Music,Music video for the song AIYOU by Eve. The son...,Music,1,"Oct 2, 2026",...,UNKNOWN,Original,2 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1900/...
30759,65098,22 Durnham Dew,UNKNOWN,22 Durnham Dew,UNKNOWN,"Slice of Life, Music",Music video for the song 22 Durnham Dew by Ben...,Music,1,"Jul 28, 2026",...,UNKNOWN,Original,1 min.,G - All Ages,UNKNOWN,30608,0,UNKNOWN,16,https://cdn.myanimelist.net/images/anime/1045/...
30760,65099,"Ghost (Music, 2026)",UNKNOWN,GHOST,UNKNOWN,"Sci-Fi, Music, Racing","Music video for the song Ghost by lIlBOI, BIG ...",Music,1,"Oct 2, 2026",...,UNKNOWN,Original,3 min.,PG-13 - Teens 13 or older,UNKNOWN,30605,0,UNKNOWN,21,https://cdn.myanimelist.net/images/anime/1833/...
30761,65100,Angels on the Dancefloor,UNKNOWN,Angels On The Dancefloor,UNKNOWN,"Music, Video Game",Music video for the song Angels On The Dancefl...,Music,1,"May 29, 2026",...,Mimoid,Original,4 min.,PG-13 - Teens 13 or older,UNKNOWN,30607,0,UNKNOWN,18,https://cdn.myanimelist.net/images/anime/1845/...
30762,65101,Goemul,Monster,괴물,UNKNOWN,Music,Music video for the song Goemul by WE GO-6.,Music,1,"Sep 22, 2026",...,UNKNOWN,Original,3 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1239/...

In [4]:
data.head()

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi, Adult Cast, Space","Crime is timeless. By the year 2071, humanity ...",TV,26,"Apr 3, 1998 to Apr 24, 1999",...,Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),50,41,90976,1077271,2089081,https://cdn.myanimelist.net/images/anime/4/196...
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi, Adult Cast, Space","Another day, another bounty—such is the life o...",Movie,1,"Sep 1, 2001",...,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),252,663,1827,234731,417292,https://cdn.myanimelist.net/images/anime/1439/...
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi, Adult Cast, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",...,Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,433,268,17956,405835,846067,https://cdn.myanimelist.net/images/anime/1130/...
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.24,"Action, Drama, Mystery, Supernatural, Detective","Though hidden away from the general public, Wi...",TV,26,"Jul 3, 2002 to Dec 25, 2002",...,Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,3558,2003,720,46691,132072,https://cdn.myanimelist.net/images/anime/10/19...
4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,6.97,"Action, Adventure, Fantasy, Shounen",It is the dark century and the people are suff...,TV,52,"Sep 30, 2004 to Sep 29, 2005",...,Toei Animation,Manga,23 min. per ep.,PG - Children,5016,6031,18,6983,16793,https://cdn.myanimelist.net/images/anime/7/215...

In [5]:
### Epsoide count
data["EpCount"] = data["Episodes"].count()
data

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL,EpCount
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi, Adult Cast, Space","Crime is timeless. By the year 2071, humanity ...",TV,26,"Apr 3, 1998 to Apr 24, 1999",...,Original,24 min. per ep.,R - 17+ (violence & profanity),50,41,90976,1077271,2089081,https://cdn.myanimelist.net/images/anime/4/196...,30763
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi, Adult Cast, Space","Another day, another bounty—such is the life o...",Movie,1,"Sep 1, 2001",...,Original,1 hr. 55 min.,R - 17+ (violence & profanity),252,663,1827,234731,417292,https://cdn.myanimelist.net/images/anime/1439/...,30763
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi, Adult Cast, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",...,Manga,24 min. per ep.,PG-13 - Teens 13 or older,433,268,17956,405835,846067,https://cdn.myanimelist.net/images/anime/1130/...,30763
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.24,"Action, Drama, Mystery, Supernatural, Detective","Though hidden away from the general public, Wi...",TV,26,"Jul 3, 2002 to Dec 25, 2002",...,Original,25 min. per ep.,PG-13 - Teens 13 or older,3558,2003,720,46691,132072,https://cdn.myanimelist.net/images/anime/10/19...,30763
4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,6.97,"Action, Adventure, Fantasy, Shounen",It is the dark century and the people are suff...,TV,52,"Sep 30, 2004 to Sep 29, 2005",...,Manga,23 min. per ep.,PG - Children,5016,6031,18,6983,16793,https://cdn.myanimelist.net/images/anime/7/215...,30763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30758,65097,AIYOU,AIYOU,AIYOU,UNKNOWN,Music,Music video for the song AIYOU by Eve. The son...,Music,1,"Oct 2, 2026",...,Original,2 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1900/...,30763
30759,65098,22 Durnham Dew,UNKNOWN,22 Durnham Dew,UNKNOWN,"Slice of Life, Music",Music video for the song 22 Durnham Dew by Ben...,Music,1,"Jul 28, 2026",...,Original,1 min.,G - All Ages,UNKNOWN,30608,0,UNKNOWN,16,https://cdn.myanimelist.net/images/anime/1045/...,30763
30760,65099,"Ghost (Music, 2026)",UNKNOWN,GHOST,UNKNOWN,"Sci-Fi, Music, Racing","Music video for the song Ghost by lIlBOI, BIG ...",Music,1,"Oct 2, 2026",...,Original,3 min.,PG-13 - Teens 13 or older,UNKNOWN,30605,0,UNKNOWN,21,https://cdn.myanimelist.net/images/anime/1833/...,30763
30761,65100,Angels on the Dancefloor,UNKNOWN,Angels On The Dancefloor,UNKNOWN,"Music, Video Game",Music video for the song Angels On The Dancefl...,Music,1,"May 29, 2026",...,Original,4 min.,PG-13 - Teens 13 or older,UNKNOWN,30607,0,UNKNOWN,18,https://cdn.myanimelist.net/images/anime/1845/...,30763
30762,65101,Goemul,Monster,괴물,UNKNOWN,Music,Music video for the song Goemul by WE GO-6.,Music,1,"Sep 22, 2026",...,Original,3 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1239/...,30763

In [9]:
data.fillna(0)

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL,EpCount
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi, Adult Cast, Space","Crime is timeless. By the year 2071, humanity ...",TV,26,"Apr 3, 1998 to Apr 24, 1999",...,Original,24 min. per ep.,R - 17+ (violence & profanity),50,41,90976,1077271,2089081,https://cdn.myanimelist.net/images/anime/4/196...,30763
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi, Adult Cast, Space","Another day, another bounty—such is the life o...",Movie,1,"Sep 1, 2001",...,Original,1 hr. 55 min.,R - 17+ (violence & profanity),252,663,1827,234731,417292,https://cdn.myanimelist.net/images/anime/1439/...,30763
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi, Adult Cast, Shounen","Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",...,Manga,24 min. per ep.,PG-13 - Teens 13 or older,433,268,17956,405835,846067,https://cdn.myanimelist.net/images/anime/1130/...,30763
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.24,"Action, Drama, Mystery, Supernatural, Detective","Though hidden away from the general public, Wi...",TV,26,"Jul 3, 2002 to Dec 25, 2002",...,Original,25 min. per ep.,PG-13 - Teens 13 or older,3558,2003,720,46691,132072,https://cdn.myanimelist.net/images/anime/10/19...,30763
4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,6.97,"Action, Adventure, Fantasy, Shounen",It is the dark century and the people are suff...,TV,52,"Sep 30, 2004 to Sep 29, 2005",...,Manga,23 min. per ep.,PG - Children,5016,6031,18,6983,16793,https://cdn.myanimelist.net/images/anime/7/215...,30763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30758,65097,AIYOU,AIYOU,AIYOU,UNKNOWN,Music,Music video for the song AIYOU by Eve. The son...,Music,1,"Oct 2, 2026",...,Original,2 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1900/...,30763
30759,65098,22 Durnham Dew,UNKNOWN,22 Durnham Dew,UNKNOWN,"Slice of Life, Music",Music video for the song 22 Durnham Dew by Ben...,Music,1,"Jul 28, 2026",...,Original,1 min.,G - All Ages,UNKNOWN,30608,0,UNKNOWN,16,https://cdn.myanimelist.net/images/anime/1045/...,30763
30760,65099,"Ghost (Music, 2026)",UNKNOWN,GHOST,UNKNOWN,"Sci-Fi, Music, Racing","Music video for the song Ghost by lIlBOI, BIG ...",Music,1,"Oct 2, 2026",...,Original,3 min.,PG-13 - Teens 13 or older,UNKNOWN,30605,0,UNKNOWN,21,https://cdn.myanimelist.net/images/anime/1833/...,30763
30761,65100,Angels on the Dancefloor,UNKNOWN,Angels On The Dancefloor,UNKNOWN,"Music, Video Game",Music video for the song Angels On The Dancefl...,Music,1,"May 29, 2026",...,Original,4 min.,PG-13 - Teens 13 or older,UNKNOWN,30607,0,UNKNOWN,18,https://cdn.myanimelist.net/images/anime/1845/...,30763
30762,65101,Goemul,Monster,괴물,UNKNOWN,Music,Music video for the song Goemul by WE GO-6.,Music,1,"Sep 22, 2026",...,Original,3 min.,PG-13 - Teens 13 or older,0,0,0,UNKNOWN,0,https://cdn.myanimelist.net/images/anime/1239/...,30763