Merging and concat

In [7]:
import numpy as np
import pandas as pd

In [16]:
employees = {
    "employee_id":[1,2,3,4,5],
    "name":["jhon","Asmin","Nitik","Ramesh","Shaym"],
    "Program":["Go","Python","PHP","Rust","R"],

}

Salaries = {
    "employee_id":[1,2,3,5,7],
    "salary":[60000,70000,90000,30000,200000],
    "bonus":[50000,10000,80000,120000,20000]
}


df1 = pd.DataFrame(employees)
df2 =pd.DataFrame(Salaries)
df1

   employee_id    name Program
0            1    jhon      Go
1            2   Asmin  Python
2            3   Nitik     PHP
3            4  Ramesh    Rust
4            5   Shaym       R

In [18]:
df2

   employee_id  salary   bonus
0            1   60000   50000
1            2   70000   10000
2            3   90000   80000
3            5   30000  120000
4            7  200000   20000

In [ ]:
pd.merge(df1,df2,on="employee_id",how="inner")

   employee_id   name Program  salary   bonus
0            1   jhon      Go   60000   50000
1            2  Asmin  Python   70000   10000
2            3  Nitik     PHP   90000   80000
3            5  Shaym       R   30000  120000

In [20]:
pd.merge(df1,df2,on="employee_id",how="outer")

   employee_id    name Program    salary     bonus
0            1    jhon      Go   60000.0   50000.0
1            2   Asmin  Python   70000.0   10000.0
2            3   Nitik     PHP   90000.0   80000.0
3            4  Ramesh    Rust       NaN       NaN
4            5   Shaym       R   30000.0  120000.0
5            7     NaN     NaN  200000.0   20000.0