Missing data

In [17]:
import numpy as np
import pandas as pd

In [21]:
data = {
    "A":[1,2,3,4,5],
    "B":[1,2,3,4,5],
    "C":[1,2,3,np.nan,np.nan],
    "D":[1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [ ]:
### Find the nan in true and false then sum how  mmay nan in column
df.isna().sum()

A    0
B    0
C    2
D    3
dtype: int64

In [24]:
## Check the null value in Column
df.isna().any()

A    False
B    False
C     True
D     True
dtype: bool

In [ ]:
## Remove Nan it drop null value row
df.dropna()

   A  B    C    D
0  1  1  1.0  1.0

In [28]:
df.dropna(thresh=3)

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
4  5  5  NaN  5.0

Filling missing data

In [29]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [30]:
df.fillna(0)

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  0.0
2  3  3  3.0  0.0
3  4  4  0.0  0.0
4  5  5  0.0  5.0

In [ ]:
value = {
    "C":300,
    "D":100
}

In [ ]:
#### Fill column wise
df.fillna(value)

   A  B      C      D
0  1  1    1.0    1.0
1  2  2    2.0  100.0
2  3  3    3.0  100.0
3  4  4  300.0  100.0
4  5  5  300.0    5.0

In [36]:
df.fillna(df.mean())

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  3.0
2  3  3  3.0  3.0
3  4  4  2.0  3.0
4  5  5  2.0  5.0